apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kuberneres.io/owner":"retail-store-sample","app.kubernetes.io/component":"service","app.kubernetes.io/instance":"ui","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ui","helm.sh/chart":"ui-0.8.4"},"name":"ui","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kuberneres.io/owner":"retail-store-sample","app.kubernetes.io/component":"service","app.kubernetes.io/instance":"ui","app.kubernetes.io/name":"ui"},"type":"NodePort"}}
  creationTimestamp: "2025-02-21T15:12:09Z"
  labels:
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ui
    helm.sh/chart: ui-0.8.4
  name: ui
  namespace: default
  resourceVersion: "702507"
  uid: 10b66b81-02d1-4dce-aff3-35e2c127e39e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.11.101
  clusterIPs:
  - 10.109.11.101
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31255
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: ui
    app.kubernetes.io/name: ui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
